apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
spec:
  # Any changes run : kubectl apply -f deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic
  
  # Properties section.
  # showGuestLoad: true when you work with Baremetal/SNMP/WMI metrics
  properties:
    repository:
      showGuestLoad: false
  # Global settings
  global:
  #  registry: index.docker.io
  #  imageUsername: turbouser
  #  imagePassword: turbopassword
    repository: turbonomic
    tag: 8.6.1
    # securitygroup required for OCP deployments
    #securityContext:
    #  fsGroup: 1000690000
    # required storageClass be Retain and WaitforFirstConsumer
    storageClassName: ibmc-vpcblock-odf-ret-general
  # remove comments from nginx if you are using OCP
  #nginx:
  #  nginxIsPrimaryIngress: false
  #  httpsRedirect: false
    #use the following parameters if you would like Turbo to create a single OCP route that will point to the nginx service
    #openshiftingress:
    #  enabled: true
    #nginxingress:
    #  enabled: true
  # Component selector - Probes
  actionscript:
    enabled: true
  appdynamics:
    enabled: true
  appinsights:
    enabled: true
  aws:
    enabled: true
  azure:
    enabled: true
  baremetal:
    enabled: false
  dynatrace:
    enabled: true
  gcp:
    enabled: true
  hpe3par:
    enabled: true
  horizon:
    enabled: false
  hyperflex:
    enabled: false
  hyperv:
    enabled: true
  ibmstorage-flashsystem:
    enabled: true
  kubeturbo:
    enabled: false
  netapp:
    enabled: true
  nutanix:
    enabled: true
  oneview:
    enabled: true
  pure:
    enabled: true
  scaleio:
    enabled: true
  servicenow:
    enabled: true
  ucs:
    enabled: true
  vcenter:
    enabled: true
  vmax:
    enabled: true
  vmm:
    enabled: false
  wmi:
    enabled: true
  snmp:
    enabled: true
  mssql:
    enabled: true
  mysql:
    enabled: true
  oracle:
    enabled: true
  tomcat:
    enabled: true
  jvm:
    enabled: true
  newrelic:
    enabled: true
  udt:
    enabled: true
  websphere:
    enabled: false
  weblogic:
    enabled: false
  xen:
    enabled: false
  instana:
    enabled: true
  jboss:
    enabled: false
