apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
spec:
  # Any changes run : kubectl apply -f deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic
  
  ### Properties section. ###
  ### showGuestLoad: true when you work with Baremetal/SNMP/WMI metrics. If you turn on, delete the repository pod to make effect ###
  properties:
    global:
      enableSecureDBConnection: true
      sqlDialect: MYSQL
      dbPort: 3306
      dbRootPassword: vmturbo
      dbRootUsername: turboadmin
    action-orchestrator:
      actionDbUsername: action
      actionDbPassword: vmturbo
    auth:
      authDbUsername: auth
      authDbPassword: vmturbo
    clustermgr:
      clustermgrDbUsername: clustermgr
      clustermgrDbPassword: vmturbo
    cost:
      costDbUsername: cost
      costDbPassword: vmturbo
    group:
      groupComponentDbUsername: group_component
      groupComponentDbPassword: vmturbo
    history:
      historyDbUsername: history
      historyDbPassword: vmturbo
    market:
      marketDbUsername: market
      marketDbPassword: vmturbo 
    plan-orchestrator:
      planDbUsername: plan
      planDbPassword: vmturbo
    repository:
      repositoryDbUsername: repository
      repositoryDbPassword: vmturbo
    suspend:
      suspendDbUsername: suspend
      suspendDbPassword: vmturbo
    topology-processor:
      topologyProcessorDbUsername: topology_processor
      topologyProcessorDbPassword: vmturbo
  # Global settings
  global:
    externalDBName: yourDB.yourURL.com
    registry: icr.io/cpopen
    repository: icr.io/cpopen/turbonomic
    tag: 8.10.1
    ### required storageClass be Retain and WaitforFirstConsumer ###
    storageClassName: gp3
  ### Component selector - Probes ###
  actionscript:
    enabled: true
  appdynamics:
    enabled: false
  appinsights:
    enabled: false
  aws:
    enabled: true
  azure:
    enabled: true
  baremetal:
    enabled: false
  datadog:
    enabled: true
  dynatrace:
    enabled: false
  gcp:
    enabled: true
  hpe3par:
    enabled: false
  horizon:
    enabled: false
  hyperflex:
    enabled: false
  hyperv:
    enabled: false
  ibmstorage-flashsystem:
    enabled: true
  kubeturbo:
    enabled: false
  netapp:
    enabled: false
  nutanix:
    enabled: false
  oneview:
    enabled: false
  pure:
    enabled: false
  scaleio:
    enabled: false
  servicenow:
    enabled: true
  ucs:
    enabled: false
  vcenter:
    enabled: true
  vmax:
    enabled: false
  vmm:
    enabled: false
  wmi:
    enabled: false
  snmp:
    enabled: false
  mssql:
    enabled: true
  mysql:
    enabled: true
  oracle:
    enabled: true
  tomcat:
    enabled: false
  jvm:
    enabled: false
  newrelic:
    enabled: false
  udt:
    enabled: true
  websphere:
    enabled: false
  weblogic:
    enabled: false
  xen:
    enabled: false
  instana:
    enabled: true
  jboss:
    enabled: false
