apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
spec:
  # Any changes run : kubectl apply -f deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic
  
  ### Properties section. ###
  ### showGuestLoad: true when you work with Baremetal/SNMP/WMI metrics. If you turn on, delete the repository pod to make effect ###
  properties:
    global:
      enableSecureDBConnection: true
      ### comentar o sqldialect se for MariaDB ###
      sqlDialect: MYSQL
      dbPort: 3306
      dbRootPassword: vmturbo
      dbRootUsername: senha_do_vmturbo
  #  repository:
  #    showGuestLoad: false
  # Global settings
  global:
    externalDBName: yourDB.yourURL.com
  #  registry: index.docker.io
  #  imageUsername: turbouser
  #  imagePassword: turbopassword
    repository: turbonomic
    tag: 8.6.4
    ### securitygroup required for OCP deployments ###
    #securityContext:
    #  fsGroup: 1000690000
    ### required storageClass be Retain and WaitforFirstConsumer ###
    storageClassName: STORAGE_CLASS_NAME
  ### remove comments from nginx if you are using OCP ###
  #nginx:
  #  nginxIsPrimaryIngress: false
  #  httpsRedirect: false
    #use the following parameters if you would like Turbo to create a single OCP route that will point to the nginx service
    #openshiftingress:
    #  enabled: true
    #nginxingress:
    #  enabled: true
  ### Component selector - Probes ###
  actionscript:
    enabled: false
  appdynamics:
    enabled: false
  appinsights:
    enabled: false
  aws:
    enabled: true
  azure:
    enabled: true
  baremetal:
    enabled: false
  dynatrace:
    enabled: false
  gcp:
    enabled: true
  hpe3par:
    enabled: false
  horizon:
    enabled: false
  hyperflex:
    enabled: false
  hyperv:
    enabled: false
  ibmstorage-flashsystem:
    enabled: false
  kubeturbo:
    enabled: false
  netapp:
    enabled: false
  nutanix:
    enabled: false
  oneview:
    enabled: false
  pure:
    enabled: false
  scaleio:
    enabled: false
  servicenow:
    enabled: false
  ucs:
    enabled: false
  vcenter:
    enabled: true
  vmax:
    enabled: false
  vmm:
    enabled: false
  wmi:
    enabled: false
  snmp:
    enabled: false
  mssql:
    enabled: false
  mysql:
    enabled: false
  oracle:
    enabled: false
  tomcat:
    enabled: false
  jvm:
    enabled: false
  newrelic:
    enabled: false
  udt:
    enabled: true
  websphere:
    enabled: false
  weblogic:
    enabled: false
  xen:
    enabled: false
  instana:
    enabled: true
  jboss:
    enabled: false
